name: Validate Manifests
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Validate Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@v1
      - name: Validate Against Kubernetes Schema
        run: kubeconform -kubernetes-version=1.28.3 -ignore-filename-pattern=.github/workflows -ignore-filename-pattern=.json$ -ignore-filename-pattern=kustomize -ignore-filename-pattern=helm -ignore-filename-pattern=yq -summary .
